Docs/winning over executives
gatsbyjs/gatsby-ja pull request #271
Opened 2020-06-28 02:49 UTC by Linus-MK

## 概要

docs/docs/winning-over-executives.md を翻訳しました。  
遅くなったことをお詫び申し上げます。

## チェック一覧

- [x] [翻訳スタイルガイド](https://github.com/gatsbyjs/gatsby-ja/blob/master/style-guide.md) に目を通しました。
- [x] [Translation Guide](https://www.gatsbyjs.org/contributing/gatsby-docs-translation-guide/#contributing-to-a-translation) に目を通しました。
- [x] `textlint` を使って校正を行いました。
- [x] 文章全体を最初から読み直して不自然な箇所が無いことを確認しました。
- [x] `Allow edits from maintainers` にチェックを入れました。

> しばらく待ってもレビューが終わらなかったり、必要なレビュー数に足りない状態が続いた場合は、[こちら](https://github.com/gatsbyjs/gatsby-ja/issues/1)からメンテナーを探して、@を付けてメンションを飛ばしてください。

## 補足

気がかりなのは以下の点です：
* Google トレンド検索のリンク先を原文のままとすべきか、日本版にするか
* ショーケースのリンクを訳出するか

Ref: #1

2020-07-04 05:47 UTC, Naturalclar commented on docs/docs/winning-over-executives.md
> +もし、Gatsby の背後にある意図の中に、重役の戦略的目標にうまく合っているものがあれば、恐れずに会話の中で戦略的目標に言及していきましょう。
原文と改行を揃えるため
```suggestion
重役に対して Gatsby のことを話す前に、彼らの戦略的目標を必ず理解しておき、Gatsby を導入しようという意見を、その具体的な目標と合致させることを確認してください。重視すべきことは、Gatsby の特徴がどのように動作するかの詳細ではなく、Gatsby の特徴がどのような結果をもたらすかです。もし、Gatsby の背後にある意図の中に、重役の戦略的目標にうまく合っているものがあれば、恐れずに会話の中で戦略的目標に言及していきましょう。
```

2020-07-04 05:49 UTC, Naturalclar commented on docs/docs/winning-over-executives.md
> +Gatsby のサイトは、他のツールで作られた同様のサイトよりも常に 2〜3 倍早く、サイトの所有者は[Gatsby にサイトを移行したあとで、リードジェネレーションが最大 60%増加した](/blog/2018-11-16-youfit-case-study/)という経験があります。
改行を原文と揃えるため、及び、フォーマットを原文と合わせるため
```suggestion
> サイトのスピードとパフォーマンスは、売上や顧客エンゲージメントに絶大な影響を与えます。[最近の Akamai の研究](https://www.akamai.com/uk/en/about/news/press/2017-press/akamai-releases-spring-2017-state-of-online-retail-performance-report.jsp)によれば、サイトのロードが 100 ミリ秒遅くなるとコンバージョンレートが 7%下がり、またモバイルユーザーの 53%はロードに 3 秒以上かかるページから離脱します。Gatsby のサイトは、他のツールで作られた同様のサイトよりも常に 2〜3 倍早く、サイトの所有者は[Gatsby にサイトを移行したあとで、リードジェネレーションが最大 60%増加した](/blog/2018-11-16-youfit-case-study/)という経験があります。
```

2020-07-04 05:49 UTC, Naturalclar commented on docs/docs/winning-over-executives.md
> +詳しくは Moz の[ページ速度が SEO に与える影響](https://moz.com/learn/seo/page-speed) をご参照ください。
```suggestion
> サイトのスピードは、Google が検索ランキングのアルゴリズムの中で使っている要素の 1 つで、サイトが遅いと SEO への悪影響が少しずつ増えていきます。
サイトが遅ければ、検索エンジンがクロールやインデックスをするのに時間がかかりますし、ユーザーの直帰率が上がり、コンバージョンレートが下がります。
そしてそれら全てがサイトの検索順位を下げるのです。Gatsby のサイトには、[Web とモバイル向けの組み込みのパフォーマンス最適化](/blog/2018-11-07-gatsby-for-apps/#why-gatsby-for-apps)があります。実のところ、Gatsby を使ってパフォーマンスが悪くなるようにするほうが苦労するくらいです。詳しくは Moz の[ページ速度が SEO に与える影響](https://moz.com/learn/seo/page-speed) をご参照ください。
```

2020-07-04 05:50 UTC, Naturalclar commented on docs/docs/winning-over-executives.md
> +複雑なツールという重荷がないので、開発チームはより集中し、より生産的になり、自分の仕事により満足するでしょう。
```suggestion
> [Gatsby ユーザー調査の結果](/blog/2019-03-05-dot-org-messaging-survey/#productive-from-the-start)、によれば、「Gatsby はまさに使い始めたときから生産性を向上させてくれます。gatsby は時間のかかる開発、ビルドツールのセットアップや設定というオーバーヘッドを取り去り、イテレーションを早めてくれます」。複雑なツールという重荷がないので、開発チームはより集中し、より生産的になり、自分の仕事により満足するでしょう。
```

2020-07-04 05:50 UTC, Naturalclar commented on docs/docs/winning-over-executives.md
> +最後に、gatsby はオープンソースなので、ソフトウェアのライセンス費用も節約できます。
```suggestion
> gatsby のサイトは、CDN に完全にデプロイされるので、従来のホスティングよりも費用が大幅に削減できます。さらに、CDN にホストすることで、トラフィックが急増したときの故障のリスクが根本的に無くなるので、リードコンバージョンの機会を逃すことがなくなります。最後に、gatsby はオープンソースなので、ソフトウェアのライセンス費用も節約できます。
```

2020-07-04 05:52 UTC, Naturalclar commented on docs/docs/winning-over-executives.md
> +<!-- Google トレンド検索のリンク先は、URLの地域指定のUSをJPに変更しました。あまり検索結果で上昇トレンドがわかりにくいのですが。 -->
:+1:

2020-07-04 05:52 UTC, Naturalclar commented on docs/docs/winning-over-executives.md
> +技術トレンドにおいてリーダーになりたい会社と、サイトパフォーマンスのような重要な要素で自社を差別化したい会社にとっては、絶好の機会でしょう。[gatsby とパートナーになる](/docs/partnering-with-gatsby/)方法をご参照ください。
```suggestion
> gatsby は、[JAMStack](https://jamstack.org/)として知られるウェブとアプリケーション開発の新たなアプローチの最前線のテクノロジーの 1 つです。
JAMStack は、CMS 中心のサイトの限界と、サーバーサイドコードの失敗点から、高速かつ軽量でモジュール式のサイト構築へと転換することを示しています。
JAMStack アプローチと gatsby とは、ここ数年で急速に人気を集め、成長が鈍化する兆しもありません。（[Google Trends における Gatsby と JAMStack](https://trends.google.com/trends/explore?date=today%205-y&geo=JP&q=jamstack,gatsby%20js)をチェックしてみてください）技術トレンドにおいてリーダーになりたい会社と、サイトパフォーマンスのような重要な要素で自社を差別化したい会社にとっては、絶好の機会でしょう。[gatsby とパートナーになる](/docs/partnering-with-gatsby/)方法をご参照ください。
```

2020-07-04 05:52 UTC, Naturalclar commented on docs/docs/winning-over-executives.md
> +もしも重役に、Gatsby のもたらす利益が、採用することによるリスクやコストを大きく上回ることを示せたら、彼らが導入を前向きに検討してくれる見込みは大きいでしょう。
```suggestion
重役は、自社のビジネスの効率や利益を向上させ、組織を成長させる方法を常に探しています。Gatsby の金銭的利益を指摘すれば、あなたの主張は通るでしょうが、しかし Gatsby が他の多くの点においてもあなたの会社のビジネスを前進させることを、詳しく述べることをわすれないでください。もしも重役に、Gatsby のもたらす利益が、採用することによるリスクやコストを大きく上回ることを示せたら、彼らが導入を前向きに検討してくれる見込みは大きいでしょう。
```

2020-07-04 05:53 UTC, Naturalclar requested changes
@Linus-MK PRありがとうございます！いくつか原文とフォーマットを揃えるためのsuggested change をしたので確認おねがいします

2020-07-29 14:30 UTC, Linus-MK commented
ごめんなさい、遅くなりました！  
suggested changeをすべて確認し、commitしました。よろしくお願いします。

2020-07-31 05:33 UTC, uetchy submitted a review, later dismissed
👍

2020-08-05 20:37 UTC, smorimoto requested changes
It's actually a fairly minor problem, but it should be fixed.

2020-08-05 20:37 UTC, smorimoto commented on docs/docs/winning-over-executives.md
> +> gatsby のサイトは、CDN に完全にデプロイされるので、従来のホスティングよりも費用が大幅に削減できます。さらに、CDN にホストすることで、トラフィックが急増したときの故障のリスクが根本的に無くなるので、リードコンバージョンの機会を逃すことがなくなります。最後に、gatsby はオープンソースなので、ソフトウェアのライセンス費用も節約できます。
```suggestion
> Gatsby のサイトは、CDN に完全にデプロイされるので、従来のホスティングよりも費用が大幅に削減できます。さらに、CDN にホストすることで、トラフィックが急増したときの故障のリスクが根本的に無くなるので、リードコンバージョンの機会を逃すことがなくなります。最後に、Gatsby はオープンソースなので、ソフトウェアのライセンス費用も節約できます。
```

2020-08-05 20:37 UTC, smorimoto commented on docs/docs/winning-over-executives.md
> +> gatsby は、[JAMStack](https://jamstack.org/)として知られるウェブとアプリケーション開発の新たなアプローチの最前線のテクノロジーの 1 つです。
```suggestion
> Gatsby は、[JAMStack](https://jamstack.org/)として知られるウェブとアプリケーション開発の新たなアプローチの最前線のテクノロジーの 1 つです。
```

2020-08-05 20:37 UTC, smorimoto commented on docs/docs/winning-over-executives.md
> +JAMStack アプローチと gatsby とは、ここ数年で急速に人気を集め、成長が鈍化する兆しもありません。（[Google Trends における Gatsby と JAMStack](https://trends.google.com/trends/explore?date=today%205-y&geo=JP&q=jamstack,gatsby%20js)をチェックしてみてください）技
```suggestion
JAMStack アプローチと Gatsby とは、ここ数年で急速に人気を集め、成長が鈍化する兆しもありません。（[Google Trends における Gatsby と JAMStack](https://trends.google.com/trends/explore?date=today%205-y&geo=JP&q=jamstack,gatsby%20js)をチェックしてみてください）技術トレンドにおいてリーダーになりたい会社と、サイトパフォーマンスのような重要な要素で自社を差別化したい会社にとっては、絶好の機会でしょう。[Gatsby とパートナーになる](/docs/partnering-with-gatsby/)方法をご参照ください。
```

2020-08-05 20:37 UTC, smorimoto commented on docs/docs/winning-over-executives.md
> +ケーススタディは、重役たちが gatsby の潜在能力を理解し gatsby の利益への実践的な洞察を得るための、素晴らしい方法です。
```suggestion
ケーススタディは、重役たちが Gatsby の潜在能力を理解し Gatsby の利益への実践的な洞察を得るための、素晴らしい方法です。
```

2020-08-05 20:37 UTC, smorimoto commented on docs/docs/winning-over-executives.md
> +gatsby サイトの例をもっと見たい場合は、[ショーケースをご覧ください](/showcase/)。
```suggestion
Gatsby サイトの例をもっと見たい場合は、[ショーケースをご覧ください](/showcase/)。
```

2020-08-09 02:58 UTC, Linus-MK commented
Oh, those should have been capital "G". I've commited the suggestions and fixed them.

2020-08-10 18:53 UTC, uetchy approved these changes

2020-08-10 21:17 UTC, smorimoto approved these changes

2020-09-02 18:29 UTC, uetchy commented
@Naturalclar @hirotaka レビューお願いします

2020-10-17 02:05 UTC, Naturalclar approved these changes

2020-10-17 02:06 UTC, merged