docs: translate docs/images and files
gatsbyjs/gatsby-ja pull request #295
Opened 2020-09-29 14:16 UTC by akthrms

## 概要

docs/images-and-files を翻訳しましたのでレビューよろしくお願いします

## チェック一覧

- [x] [翻訳スタイルガイド](https://github.com/gatsbyjs/gatsby-ja/blob/master/style-guide.md) に目を通しました。
- [x] [Translation Guide](https://www.gatsbyjs.org/contributing/gatsby-docs-translation-guide/#contributing-to-a-translation) に目を通しました。
- [x] `textlint` を使って校正を行いました。
- [x] 文章全体を最初から読み直して不自然な箇所が無いことを確認しました。
- [x] `Allow edits from maintainers` にチェックを入れました。

> しばらく待ってもレビューが終わらなかったり、必要なレビュー数に足りない状態が続いた場合は、[こちら](https://github.com/gatsbyjs/gatsby-ja/issues/1)からメンテナーを探して、@を付けてメンションを飛ばしてください。

## 補足

Ref: #1

2020-10-17 02:08 UTC, Naturalclar commented on docs/docs/images-and-files.md
> +Gatsby は、画像、ビデオ、ファイルをプロジェクトに追加するための複数のソリューションを提供しています。プロのアドバイス：必ずしも GraphQL を使用する必要はありません！[インポート](/docs/importing-assets-into-files/)や[static フォルダー](/docs/static-folder/)の使用から、画像の肥大化を防ぐための[Gatsby Ima
プロのアドバイス、と言う表現は日本語では伝わりにくいと感じました
```suggestion
Gatsby は、画像、ビデオ、ファイルをプロジェクトに追加するための複数のソリューションを提供しています。また、必ずしも GraphQL を使用する必要はありません！[インポート](/docs/importing-assets-into-files/)や[static フォルダー](/docs/static-folder/)の使用から、画像の肥大化を防ぐための[Gatsby Image](/docs/using-gatsby-image/)を使ったダイナミッククエリまで、様々なオプションが用意されています。
```

2020-10-17 02:09 UTC, Naturalclar commented on docs/docs/images-and-files.md
> +title: 画像、ファイル、ビデオ in Gatsby
in Gatsby は日本語では不自然な表現かなと感じました
```suggestion
title: Gatsby での画像、ファイル、ビデオの取り扱いについて
```

2020-10-17 02:09 UTC, Naturalclar requested changes
@akthrms PR ありがとうございます！すこしコメントしたのでお手すきの際に確認お願いします！

2020-10-17 11:55 UTC, akthrms commented
> @akthrms PR ありがとうございます！すこしコメントしたのでお手すきの際に確認お願いします！

@Naturalclar 
コメントありがとうございます！修正いたしましたのでご確認よろしくお願いします

2020-10-17 13:57 UTC, uetchy commented on docs/docs/images-and-files.md
> +Gatsby は、画像、ビデオ、ファイルをプロジェクトに追加するための複数のソリューションを提供しています。また、必ずしも GraphQL を使用する必要はありません！[インポート](/docs/importing-assets-into-files/)や[static フォルダー](/docs/static-folder/)の使用から、画像の肥大化を防ぐための[Gatsby Image](/d
```suggestion
Gatsby は、画像、ビデオ、ファイルをプロジェクトに追加するための複数のソリューションを提供しています。また、必ずしも GraphQL を使用する必要はありません！[インポート](/docs/importing-assets-into-files/)や [static フォルダー](/docs/static-folder/)の使用から、画像の肥大化を防ぐための [Gatsby Image](/docs/using-gatsby-image/) を使ったダイナミッククエリまで、様々なオプションが用意されています。
```

2020-10-17 13:57 UTC, uetchy approved these changes

2020-10-19 07:06 UTC, Naturalclar approved these changes
@akthrms ありがとうございます！

2020-10-19 07:06 UTC, merged