docs: translate docs/interactive-pages
gatsbyjs/gatsby-ja pull request #330
Opened 2021-03-19 14:32 UTC by yuzinet

## 概要

## チェック一覧

- [ ] [翻訳スタイルガイド](https://github.com/gatsbyjs/gatsby-ja/blob/master/style-guide.md) に目を通しました。
- [ ] [Translation Guide](https://www.gatsbyjs.org/contributing/gatsby-docs-translation-guide/#contributing-to-a-translation) に目を通しました。
- [ ] `textlint` を使って校正を行いました。
- [ ] 文章全体を最初から読み直して不自然な箇所が無いことを確認しました。
- [ ] `Allow edits from maintainers` にチェックを入れました。

> しばらく待ってもレビューが終わらなかったり、必要なレビュー数に足りない状態が続いた場合は、[こちら](https://github.com/gatsbyjs/gatsby-ja/issues/1)からメンテナーを探して、@を付けてメンションを飛ばしてください。

## 補足

Ref: #1

2021-03-24 06:22 UTC, yuzinet commented
@hirotaka @uetchy @Naturalclar 
rebase this branch and passed github actions linter.
Could you confirm and merge this PR?

2021-03-26 13:28 UTC, yuzinet commented
@hirotaka @uetchy @Naturalclar 
Could confirm this ?

2021-04-02 13:18 UTC, yuzinet commented
@hirotaka @uetchy @Naturalclar 
Could you guys confirm this PR?
or please tell me how to proceed PR review?

2021-04-09 21:49 UTC, yuzinet commented
@hirotaka  @uetchy  @Naturalclar 
何度も申し訳ないですがこちらレビューを通して頂けないでしょうか。
よろしくお願いします。

2021-04-24 14:19 UTC, Naturalclar commented on docs/docs/interactive-pages.md
> +この [Gatsby スタイルガイド](/contributing/gatsby-style-guide/) にしたがって Pull Request を承認します。
元文の意味から逸脱してしまっています。
多少上長になりますが、
```
Pull Request が承認されることを確実にするために、スタイルガイドに沿って Pull Request を作成してください。
```
などが良いかなと

2021-04-24 14:19 UTC, Naturalclar requested changes
反応が遅れて申し訳ありません、コメントしたので確認おねがいします

2021-04-25 09:27 UTC, yuzinet commented on docs/docs/interactive-pages.md
> +この [Gatsby スタイルガイド](/contributing/gatsby-style-guide/) にしたがって Pull Request を承認します。
ありがとうございます。
確認して修正します。

2021-04-25 12:53 UTC, yuzinet commented on docs/docs/interactive-pages.md
> +この [Gatsby スタイルガイド](/contributing/gatsby-style-guide/) にしたがって Pull Request を承認します。
@Naturalclar 

`Pull Request` が冗長かと思いますが意味は通っていると思います。

修正したので確認およびレビューを進めていただけますでしょうか。

よろしくお願いします。

2021-05-01 12:04 UTC, yuzinet commented
> 反応が遅れて申し訳ありません、コメントしたので確認おねがいします

こちら修正しているので確認いただけますか？
よろしくお願いします。

2021-05-07 01:57 UTC, yuzinet commented
@hirotaka @Naturalclar (@uetchy )
こちらご確認お願いします。

@Naturalclar 
レビューの修正対応しているのですがご確認頂けていますでしょうか？

お手数ですがご確認お願いします。

2021-05-25 12:49 UTC, yuzinet commented
@Naturalclar @hirotaka @uetchy 

こちらいかがでしょうか？

2022-01-02 20:29 UTC, yuzinet commented
@hirotaka @uetchy @Naturalclar
こちらご確認お願いします

2022-02-04 13:59 UTC, yuzinet commented
@hirotaka @uetchy @Naturalclar
こちらご確認お願いします

2022-04-14 20:40 UTC, yuzinet commented
@hirotaka @uetchy @Naturalclar
こちらご確認お願いします

2025-01-20 16:36 UTC, closed without merging